# Generated by Django 3.2.7 on 2021-11-27 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barraca',
            fields=[
                ('barraca_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_barraca', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone_responsavel', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_barraca', models.CharField(blank=True, max_length=5, null=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feira',
            fields=[
                ('feira_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_feira', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('endereco_cep', models.CharField(max_length=8)),
                ('endereco_uf', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2)),
                ('endereco_cidade', models.CharField(max_length=100)),
                ('endereco_bairro', models.CharField(max_length=50)),
                ('endereco_logradouro', models.CharField(max_length=50)),
                ('endereco_complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('dia_semana', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListaCompras',
            fields=[
                ('lista_id', models.AutoField(primary_key=True, serialize=False)),
                ('responsavel', models.ForeignKey(db_column='fk_responsavel_id', on_delete=django.db.models.deletion.CASCADE, related_name='lista_responsavel_fk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('produto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.IntegerField()),
                ('unidade', models.CharField(max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('barraca', models.ForeignKey(db_column='fk_barraca_id', on_delete=django.db.models.deletion.CASCADE, related_name='produto_barraca_fk', to='projeto.barraca')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoListaCompras',
            fields=[
                ('produtolista_id', models.AutoField(primary_key=True, serialize=False)),
                ('lista_compras', models.ForeignKey(db_column='fk_lista_id', on_delete=django.db.models.deletion.CASCADE, related_name='produtolista_lista_fk', to='projeto.listacompras')),
                ('produto', models.ForeignKey(db_column='fk_produto_id', on_delete=django.db.models.deletion.CASCADE, related_name='produtolista_produto_fk', to='projeto.produto')),
            ],
        ),
        migrations.AddField(
            model_name='barraca',
            name='feira',
            field=models.ForeignKey(db_column='fk_feira_id', on_delete=django.db.models.deletion.CASCADE, related_name='barraca_feira_fk', to='projeto.feira'),
        ),
        migrations.AddField(
            model_name='barraca',
            name='responsavel',
            field=models.ForeignKey(db_column='fk_responsavel_id', on_delete=django.db.models.deletion.CASCADE, related_name='barraca_responsavel_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
