# Generated by Django 3.2.9 on 2021-11-27 19:51

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', models.CharField(max_length=11)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Barraca',
            fields=[
                ('barraca_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_barraca', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone_responsavel', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_barraca', models.CharField(blank=True, max_length=5, null=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feira',
            fields=[
                ('feira_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_feira', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('endereco_cep', models.CharField(max_length=8)),
                ('endereco_uf', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2)),
                ('endereco_cidade', models.CharField(max_length=100)),
                ('endereco_bairro', models.CharField(max_length=50)),
                ('endereco_logradouro', models.CharField(max_length=50)),
                ('endereco_complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('dia_semana', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ListaCompras',
            fields=[
                ('lista_id', models.AutoField(primary_key=True, serialize=False)),
                ('responsavel', models.ForeignKey(db_column='fk_responsavel_id', on_delete=django.db.models.deletion.CASCADE, related_name='lista_responsavel_fk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('produto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoListaCompras',
            fields=[
                ('produtolista_id', models.AutoField(primary_key=True, serialize=False)),
                ('lista_compras', models.ForeignKey(db_column='fk_lista_id', on_delete=django.db.models.deletion.CASCADE, related_name='produtolista_lista_fk', to='projeto.listacompras')),
                ('produto', models.ForeignKey(db_column='fk_produto_id', on_delete=django.db.models.deletion.CASCADE, related_name='produtolista_produto_fk', to='projeto.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoBarraca',
            fields=[
                ('produtobarraca_id', models.AutoField(primary_key=True, serialize=False)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unidade', models.CharField(max_length=10)),
                ('quantidade', models.IntegerField()),
                ('barraca', models.ForeignKey(db_column='fk_barraca_id', on_delete=django.db.models.deletion.CASCADE, related_name='produtobarraca_barraca_fk', to='projeto.barraca')),
                ('produto', models.ForeignKey(db_column='fk_produto_id', on_delete=django.db.models.deletion.CASCADE, related_name='produtobarraca_produto_fk', to='projeto.produto')),
            ],
        ),
        migrations.AddField(
            model_name='barraca',
            name='feira',
            field=models.ForeignKey(db_column='fk_feira_id', on_delete=django.db.models.deletion.CASCADE, related_name='barraca_feira_fk', to='projeto.feira'),
        ),
        migrations.AddField(
            model_name='barraca',
            name='responsavel',
            field=models.ForeignKey(db_column='fk_responsavel_id', on_delete=django.db.models.deletion.CASCADE, related_name='barraca_responsavel_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
