# Generated by Django 3.2.7 on 2021-11-27 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='barraca',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='unidade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='valor',
        ),
        migrations.CreateModel(
            name='ProdutoBarraca',
            fields=[
                ('produtobarraca_id', models.AutoField(primary_key=True, serialize=False)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unidade', models.CharField(max_length=10)),
                ('quantidade', models.IntegerField()),
                ('barraca', models.ForeignKey(db_column='fk_barraca_id', on_delete=django.db.models.deletion.CASCADE, related_name='produtobarraca_barraca_fk', to='projeto.barraca')),
                ('produto', models.ForeignKey(db_column='fk_produto_id', on_delete=django.db.models.deletion.CASCADE, related_name='produtobarraca_produto_fk', to='projeto.produto')),
            ],
        ),
    ]
