# Generated by Django 3.2.7 on 2021-11-29 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_auto_20211128_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listacompras',
            old_name='responsavel',
            new_name='cliente',
        ),
        migrations.AddField(
            model_name='listacompras',
            name='produto',
            field=models.ForeignKey(db_column='fk_produto_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lista_produto_fk', to='projeto.produto'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='listacompras',
            unique_together={('cliente', 'produto')},
        ),
        migrations.DeleteModel(
            name='ProdutoListaCompras',
        ),
    ]
